src/Entity/Articles.php
<?php

namespace App\Entity;

use App\Repository\ArticlesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticlesRepository::class)]
class Articles
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $author = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;
    
    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?Animals $animals = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?Breed $breed = null;

    #[ORM\Column(length: 255)]
    private ?string $img = null;

    // dans le construct je mets created_at et updated_at en datetimeimmutable comme ca ca se fait tout seul dans la db
    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->updated_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getAnimals(): ?Animals
    {
        return $this->animals;
    }

    public function setAnimals(?Animals $animals): static
    {
        $this->animals = $animals;

        return $this;
    }

    public function getBreed(): ?Breed
    {
        return $this->breed;
    }

    public function setBreed(?Breed $breed): static
    {
        $this->breed = $breed;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): static
    {
        $this->img = $img;

        return $this;
    }
}

src/Form/ArticlesType.php
<?php

namespace App\Form;

use App\Entity\animals;
use App\Entity\Articles;
use App\Entity\Breed;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticlesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('author', null, [
                'label' => 'Auteur/e',
            ])
            ->add('description', null, [
                'label' => 'Description',
            ])
            ->add('animals', EntityType::class, [
                'class' => animals::class,
                'choice_label' => 'name',
                'label' => 'Animal',
            ])
            ->add('breed', EntityType::class, [
                'class' => Breed::class,
                'choice_label' => 'name',
                'required' => false,
                'label' => 'Race',
            ])
            ->add('img', FileType::class, [
                'label' => 'Image',
                'mapped' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Articles::class,
        ]);
    }
}

src/Controller/ArticlesController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use App\Form\ArticlesType;
use App\Repository\ArticlesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/articles')]
final class ArticlesController extends AbstractController
{
    #[Route(name: 'app_articles_index', methods: ['GET'])]
    public function index(ArticlesRepository $articlesRepository): Response
    {
        return $this->render('articles/index.html.twig', [
            'articles' => $articlesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_articles_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $article = new Articles();
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $file = ($form->get('img')->getData());

            if ($file) {
                // tu créer newfilename pour changer le nom de l'image 
                // time va convertir en integer l'heure ou le moment ou l'image a été uploadé
                // getClientOriginalName va prendre le nom de l'image depuis le pc ou autre device ou ca 
                $newFileName = time() . '-' . $file->getClientOriginalName();

                $file->move($this->getParameter('article_dir'), $newFileName);

                $article->setImg($newFileName);

            }

            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('app_articles_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('articles/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_articles_show', methods: ['GET'])]
    public function show(Articles $article): Response
    {
        return $this->render('articles/show.html.twig', [
            'article' => $article,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_articles_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Articles $article, EntityManagerInterface $entityManager, ArticlesRepository $articlesRepository, $id): Response
    {
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = ($form->get('img')->getData());
            $oldImage = $article->getImg();
            

            if ($file) {
                $newFileName = time() . '-' . $file->getClientOriginalName();
                $file->move($this->getParameter('article_dir'), $newFileName);
                unlink($this->getParameter('article_dir') . '/' . $oldImage);
                $article->setImg($newFileName);
            }

            $entityManager->flush();

            return $this->redirectToRoute('app_articles_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('articles/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_articles_delete', methods: ['POST'])]
    public function delete(Request $request, Articles $article, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->getPayload()->getString('_token'))) {
            $image = $article->getImg();
            unlink($this->getParameter('article_dir') . '/' . $image);
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_articles_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/articles/_delete_form.html.twig
<form method="post" action="{{ path('app_articles_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/articles/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/articles/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification d'articles{% endblock %}

{% block body %}
    <h1>Modification d'articles</h1>

    {{ include('articles/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    <a href="{{ path('app_articles_index') }}">Retour à la liste</a>

    {{ include('articles/_delete_form.html.twig') }}
{% endblock %}

templates/articles/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page d'accueil des articles{% endblock %}

{% block body %}
    <div class="main-content">
        <h1>Page d'accueil des articles</h1>

        <div class="table-container">
            <table class="table">
        <thead>
            <tr>
                <th>Auteur/e</th>
                <th>Nom de l'animal</th>
                <th>Race de l'animal</th>
                <th>Description</th>
                <th>Image</th>
                <th>Crée le</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.author }}</td>
                <td>{{ article.animals.name }}</td>
                <td>{{ article.breed.name }}</td>
                <td>{{ article.description }}</td>
                <td>
                    {% if article.img %}
                        <img src="{{ asset('upload/articles/' ~ article.img) }}" alt="Image de {{ article.animals.name }}" style="max-width: 100px; max-height: 100px;">
                     {% else %}
                        Aucune image
                    {% endif %}
                </td>
                <td>{{ article.createdAt ? article.createdAt|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_articles_show', {'id': article.id}) }}" class="btn btn-secondary">Voir</a>
                    <a href="{{ path('app_articles_edit', {'id': article.id}) }}" class="btn">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">aucun enregistrement trouvé</td>
            </tr>
        {% endfor %}
            </tbody>
            </table>
        </div>

        <div style="text-align: center; margin-top: 2rem;">
            <a href="{{ path('app_articles_new') }}" class="btn">Créer un nouvel article</a>
        </div>
    </div>
{% endblock %}

templates/articles/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les articles{% endblock %}

{% block body %}
    <h1>Créer un nouvel article</h1>

    {{ include('articles/_form.html.twig') }}

    <a href="{{ path('app_articles_index') }}">retour à la liste</a>
{% endblock %}

templates/articles/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles{% endblock %}

{% block body %}
    <h1>Articles</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Auteur/e</th>
                <td>{{ article.author }}</td>
            </tr>
            <tr>
            <tr>
                <th>Image : </th>
                <td>
                    {% if article.img %}
                        <img src="{{ asset('upload/articles/' ~ article.img) }}" alt="Image de {{ article.animals.name }}" style="max-width: 100px; max-height: 100px;">
                     {% else %}
                        Aucune image
                    {% endif %}
                </td>
            </tr>
                <th>Description : </th>
                <td>{{ article.description }}</td>
            </tr>
            <tr>
                <th>Crée le : </th>
                <td>{{ article.createdAt ? article.createdAt|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Dernière modification le : </th>
                <td>{{ article.updatedAt ? article.updatedAt|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_articles_index') }}">Retour à la liste</a>

    <a href="{{ path('app_articles_edit', {'id': article.id}) }}">Modifier</a>

    {{ include('articles/_delete_form.html.twig') }}
{% endblock %}